In [18]:
import tensorflow as tf

In [22]:
tf.__version__

'2.9.1'

In [23]:
A = tf.constant([4, 2, 2])
A

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([4, 2, 2], dtype=int32)>

In [24]:
tf.one_hot(A, depth=6)

<tf.Tensor: shape=(3, 6), dtype=float32, numpy=
array([[0., 0., 0., 0., 1., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.]], dtype=float32)>